/*
 * Description: Protocols for parser outputs.
 *
 * Copyright (C) 2022-2023 Danny McClanahan <dmcC2@hypnicjerk.ai>
 * SPDX-License-Identifier: LGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! Protocols for parser outputs.

/* #![warn(missing_docs)] */
/* #![deny(rustdoc::missing_crate_level_docs)] */
/* Make all doctests fail if they produce any warnings. */
#![doc(test(attr(deny(warnings))))]
#![deny(clippy::all)]

pub trait Input {}
pub trait Output {}

pub trait Parser {
  type I: Input;
  type O: Output;
}

/// "argument specification" for a token
#[derive(Clone, PartialEq, Eq)]
pub enum ArgSpec {
  /// no arguments means each instance of this token is indistinguishable from the others
  NoArguments,
  /// may take some arguments
  SomeArguments,
}

/// a class of tokens for the output, which may accept parameters
pub trait Tag {
  fn arg_spec(&self) -> &ArgSpec;
}

/// individual "parse entries" i.e. [`low_level::ParseEntry`] generated by an active parse will
/// reference a type-erased handle [`low_level::Symbol`] instead of a typed [`Tag`] object.
pub mod low_level {
  /// internally generated handle to represent a [`super::Tag`] instance
  #[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
  pub struct Symbol(pub usize);

  pub struct ParseEntry<I> {
    key: Symbol,
    args: Option<Vec<I>>,
  }
}
